replicaCount: 1
image:
  repositoryPrefix: "ghcr.io/noureddine-t"
  tag: "111e5ba737d9f12575465f6ecfabede2abb547d9"
  pullPolicy: Always
ingress:
  enabled: true
  className: traefik
  host: calculatrice-taleb.duckdns.org
  certManagerIssuer: letsencrypt-prod
