apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:blue
    name: kuard-container
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThreshold: 3
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "50m"
        memory: "128Mi"
