apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: frontend
    soft: kuard
  name: kuard-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      soft: kuard
  template:
    metadata:
      labels:
        app: frontend
        soft: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-container
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP