apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer-replicaset
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-consumer:taleb.latest
          resources:
            requests:
              cpu: 50m
              memory: 56Mi