# Default values for the calculatrice app

replicaCount: 1
image:
  repositoryPrefix: "ghcr.io/noureddine-t"
  tag: "adbf0edc3feb98c79f80460d71540eae18adfa5a"
  pullPolicy: Always
ingress:
  enabled: true
  className: traefik
  host: calculatrice-taleb.duckdns.org
  certManagerIssuer: letsencrypt-prod
redis:
  port: 6379
rabbitmq:
  amqpPort: 5672
  managementPort: 15672
