# Default values for the calculatrice app

replicaCount: 1
image:
  repositoryPrefix: "ghcr.io/noureddine-t"
  tag: "d5b14ff7d50203f91e353776ef6c83b471b234da"
  pullPolicy: Always
ingress:
  enabled: true
  className: traefik
  host: calculatrice-taleb.duckdns.org
  certManagerIssuer: letsencrypt-prod
redis:
  port: 6379
rabbitmq:
  amqpPort: 5672
  managementPort: 15672
