apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: app-frontend
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
