apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-replicaset
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/app-frontend:talebv6
          resources:
            requests:
              cpu: 50m
              memory: 56Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP