services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  backend-api:
    build:
      context: ./backend
    container_name: backend-api
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - rabbitmq

  backend-consumer:
    build:
      context: ./consumer
    container_name: backend-consumer
    depends_on:
      - redis
      - rabbitmq

  app-frontend:
    build:
      context: ./frontend
    container_name: app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-api
      - backend-consumer


