services:
  redis:
    image: redis
    container_name: myRedis
    ports:
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: myRabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"


  backend-api:
    build:
      context: ./backend
    image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-api:taleb
    container_name: backend-api
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq

  backend-consumer:
    build:
      context: ./consumer
    image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-consumer:taleb
    container_name: backend-consumer
    depends_on:
      - redis
      - rabbitmq

  app-frontend:
    build:
      context: ./frontend
    image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/app-frontend:taleb
    container_name: app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-api
      - backend-consumer


