apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.image.repositoryPrefix }}/calculatrice-front:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 50m
              memory: 56Mi
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
