apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitMQ-replicaset
  labels:
    app: rabbitMQ
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitMQ
  template:
    metadata:
      labels:
        app: rabbitMQ
    spec:
      containers:
        - name: rabbitMQ-container
          image: rabbitmq:3.12-management
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
      