name: CI/CD Workflow (build, push, and deploy)

on:
  push:
    branches:
      - main
    paths:
      - "Application/**"
      - "Kubernetes/**"
      - ".github/workflows/**"
      - "!Application/README.md"
      - "!Application/docker-compose.yaml"
      - "!Kubernetes/README.md"

env:
  FRONT_WORKING_DIRECTORY: Application/frontend
  API_WORKING_DIRECTORY: Application/backend
  CONSUMER_WORKING_DIRECTORY: Application/consumer
  # Use GitHub Container Registry (GHCR)
  FRONT_LOCATION: ghcr.io/${{ github.repository_owner }}/calculatrice-front:latest
  API_LOCATION: ghcr.io/${{ github.repository_owner }}/calculatrice-api:latest
  CONSUMER_LOCATION: ghcr.io/${{ github.repository_owner }}/calculatrice-consumer:latest

  REDIS_PATH: Kubernetes/redis
  RABBITMQ_PATH: Kubernetes/rabbitMQ
  FRONT_PATH: Kubernetes/front
  NGINX_INGRESS_PATH: "Kubernetes/ingress-nginx"
  API_PATH: Kubernetes/api
  CONSUMER_PATH: Kubernetes/consumer
  NAMESPACE: taleb

jobs:
  build-and-push-front:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU (pour architecture ARM)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Frontend (ARM64)
        if: contains(github.event.head_commit.modified, 'Application/frontend/')
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.FRONT_WORKING_DIRECTORY }}
          push: true
          platforms: linux/arm64
          tags: ${{ env.FRONT_LOCATION }}

  build-and-push-api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push API (ARM64)
        if: contains(github.event.head_commit.modified, 'Application/backend/')
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.API_WORKING_DIRECTORY }}
          push: true
          platforms: linux/arm64
          tags: ${{ env.API_LOCATION }}

  build-and-push-consumer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Consumer (ARM64)
        if: contains(github.event.head_commit.modified, 'Application/consumer/')
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONSUMER_WORKING_DIRECTORY }}
          push: true
          platforms: linux/arm64
          tags: ${{ env.CONSUMER_LOCATION }}

  deploy-with-kubernetes:
    runs-on: ubuntu-latest
    needs: [build-and-push-front, build-and-push-api, build-and-push-consumer]
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Create .kube directory"
        run: mkdir -p $HOME/.kube

      - name: "Set up Kubernetes configuration"
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: "Deploy to Kubernetes"
        run: |
          # Création du namespace s'il n'existe pas
          kubectl create namespace ${{ env.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
          kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

          # Appliquer les manifests
          kubectl apply -f ${{ env.RABBITMQ_PATH }}/rabbitmq-replicaset.yaml
          kubectl apply -f ${{ env.RABBITMQ_PATH }}/rabbitmq-service.yaml

          kubectl apply -f ${{ env.REDIS_PATH }}/redis-replicaset.yaml
          kubectl apply -f ${{ env.REDIS_PATH }}/redis-service.yaml

          kubectl apply -f ${{ env.FRONT_PATH }}/front-replicaset.yaml
          kubectl apply -f ${{ env.FRONT_PATH }}/front-service.yaml

          kubectl apply -f ${{ env.NGINX_INGRESS_PATH }}/nginx-ingress.yaml

          kubectl apply -f ${{ env.API_PATH }}/api-replicaset.yaml
          kubectl apply -f ${{ env.API_PATH }}/api-service.yaml

          kubectl apply -f ${{ env.CONSUMER_PATH }}/consumer-replicaset.yaml