name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REDIS_PATH: Kubernetes/redis
      RABBITMQ_PATH: Kubernetes/rabbitMQ
      FRONT_PATH: Kubernetes/front
      NGINX_INGRESS_PATH: "Kubernetes/ingress-nginx"
      API_PATH: Projet/Kubernetes/api
      CONSUMER_PATH: Projet/Kubernetes/consumer
      NAMESPACE: taleb

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Create .kube directory"
        run: mkdir -p $HOME/.kube

      - name: "Set up Kubernetes configuration"
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: "Deploy to Kubernetes"
        run: |
          kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

          kubectl apply -f ${{ env.RABBITMQ_PATH }}/rabbitmq-replicaset.yaml
          kubectl apply -f ${{ env.RABBITMQ_PATH }}/rabbitmq-service.yaml
          
          kubectl apply -f ${{ env.REDIS_PATH }}/redis-replicaset.yaml
          kubectl apply -f ${{ env.REDIS_PATH }}/redis-service.yaml

          kubectl apply -f ${{ env.FRONT_PATH }}/front-replicaset.yaml
          kubectl apply -f ${{ env.FRONT_PATH }}/front-service.yaml

          kubectl apply -f ${{ env.NGINX_INGRESS_PATH }}/nginx-ingress.yaml

          kubectl apply -f ${{ env.API_PATH }}/api-replicaset.yaml
          kubectl apply -f ${{ env.API_PATH }}/api-service.yaml

          kubectl apply -f ${{ env.CONSUMER_PATH }}/consumer-replicaset.yaml
